In [2]:
import numpy as np

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-0.0543163 ,  0.2838607 ,  0.86589007],
       [-1.21727323, -0.34154523, -0.71836949]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [1, 2, 3]
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('int64')

In [24]:
arr3 = np.zeros((10, 1))
arr3

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [26]:
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [1]:
import torch

In [2]:
torch.__version__

'1.11.0'